/**
 * Here, graph generators are introduced that generate the
 * initial graph instance of a dynamic graph.
 * Afterwards, the dynamics are created by the updates
 * contained in batches and generated by batch generators.
 */
package dna.examples.graphs.generators;

